// <auto-generated />
namespace EkinciProject.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ekinci : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ekinci));
        
        string IMigrationMetadata.Id
        {
            get { return "201902281130484_Ekinci"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
